export const ProductService = {
  getProductsData() {
    return [
      {
        id: "1000",
        number: "f230fh0g3",
        sourceLanguage:
          "Smartcat enables smooth, efficient teamwork and doesn’t charge to add new users",
        machineLanguage:
          "Smartcat permite un trabajo en equipo fluido y eficiente y no cobra por agregar nuevos usuarios.",
        description: "Product Description",
        image: "bamboo-watch.jpg",
        price: 65,
        category: "Accessories",
        quantity: 24,
        inventoryStatus: "MODIFIED",
        rating: 5,
      },

      {
        ID: 1,
        NODE_ID: "node_u2dc_1",
        SOURCE_CONTENT: "GRADE1",
        TRANSLATED_CONTENT: " GRADE ",
        EDITED_CONTENT: null,
        IS_ACTIVE: 1,
        CREATED_BY: null,
        CREATED_DATE: "2024-05-08 16:13:42",
        MODIFIED_BY: null,
        MODIFIED_DATE: "2024-05-22 18:27:03",
        JOB_DETAILS_ID: 7,
        PAGE_NO: null,
        id: 1,
      },
      {
        ID: 2,
        NODE_ID: "node_u2dc_2",
        SOURCE_CONTENT: "•  UNIT1",
        TRANSLATED_CONTENT: "  •  UNIT ",
        EDITED_CONTENT: null,
        IS_ACTIVE: 1,
        CREATED_BY: null,
        CREATED_DATE: "2024-05-08 16:13:42",
        MODIFIED_BY: null,
        MODIFIED_DATE: "2024-05-22 18:27:03",
        JOB_DETAILS_ID: 7,
        PAGE_NO: null,
        id: 2,
      },
      {
        ID: 3,
        NODE_ID: "node_u2dc_3",
        SOURCE_CONTENT: "•  SECTION",
        TRANSLATED_CONTENT: "  •  SECTION ",
        EDITED_CONTENT: null,
        IS_ACTIVE: 1,
        CREATED_BY: null,
        CREATED_DATE: "2024-05-08 16:13:42",
        MODIFIED_BY: null,
        MODIFIED_DATE: "2024-05-22 18:27:04",
        JOB_DETAILS_ID: 7,
        PAGE_NO: null,
        id: 3,
      },
      {
        ID: 4,
        NODE_ID: "node_u2dc_4",
        SOURCE_CONTENT: "•  LESSON",
        TRANSLATED_CONTENT: "  •  LESSON ",
        EDITED_CONTENT: null,
        IS_ACTIVE: 1,
        CREATED_BY: null,
        CREATED_DATE: "2024-05-08 16:13:42",
        MODIFIED_BY: null,
        MODIFIED_DATE: "2024-05-22 18:27:04",
        JOB_DETAILS_ID: 7,
        PAGE_NO: null,
        id: 4,
      },
      {
        ID: 5,
        NODE_ID: "node_u2fb_1",
        SOURCE_CONTENT: "GRADE",
        TRANSLATED_CONTENT: " GRADE ",
        EDITED_CONTENT: null,
        IS_ACTIVE: 1,
        CREATED_BY: null,
        CREATED_DATE: "2024-05-08 16:13:42",
        MODIFIED_BY: null,
        MODIFIED_DATE: "2024-05-22 18:27:04",
        JOB_DETAILS_ID: 7,
        PAGE_NO: null,
        id: 5,
      },
      {
        ID: 6,
        NODE_ID: "node_u2fb_2",
        SOURCE_CONTENT: "•  UNIT",
        TRANSLATED_CONTENT: "  •  UNIT ",
        EDITED_CONTENT: null,
        IS_ACTIVE: 1,
        CREATED_BY: null,
        CREATED_DATE: "2024-05-08 16:13:42",
        MODIFIED_BY: null,
        MODIFIED_DATE: "2024-05-22 18:27:05",
        JOB_DETAILS_ID: 7,
        PAGE_NO: null,
        id: 6,
      },
      {
        ID: 7,
        NODE_ID: "node_u2fb_3",
        SOURCE_CONTENT: "•  SECTION",
        TRANSLATED_CONTENT: "  •  SECTION ",
        EDITED_CONTENT: null,
        IS_ACTIVE: 1,
        CREATED_BY: null,
        CREATED_DATE: "2024-05-08 16:13:42",
        MODIFIED_BY: null,
        MODIFIED_DATE: "2024-05-22 18:27:05",
        JOB_DETAILS_ID: 7,
        PAGE_NO: null,
        id: 7,
      },
      {
        ID: 16,
        NODE_ID: "node_u41f_1",
        SOURCE_CONTENT: "Activity 1",
        TRANSLATED_CONTENT: "Activity 1",
        EDITED_CONTENT: null,
        IS_ACTIVE: 1,
        CREATED_BY: null,
        CREATED_DATE: "2024-05-08 16:13:42",
        MODIFIED_BY: null,
        MODIFIED_DATE: "2024-05-22 18:27:10",
        JOB_DETAILS_ID: 7,
        PAGE_NO: null,
        id: 16,
      },
      {
        ID: 17,
        NODE_ID: "node_u436_1",
        SOURCE_CONTENT: "Activity 2",
        TRANSLATED_CONTENT: "Activity 2",
        EDITED_CONTENT: null,
        IS_ACTIVE: 1,
        CREATED_BY: null,
        CREATED_DATE: "2024-05-08 16:13:42",
        MODIFIED_BY: null,
        MODIFIED_DATE: "2024-05-22 18:27:10",
        JOB_DETAILS_ID: 7,
        PAGE_NO: null,
        id: 17,
      },
      {
        ID: 18,
        NODE_ID: "node_u44d_1",
        SOURCE_CONTENT: "Lesson Synthesis",
        TRANSLATED_CONTENT: "Lesson Synthesis",
        EDITED_CONTENT: null,
        IS_ACTIVE: 1,
        CREATED_BY: null,
        CREATED_DATE: "2024-05-08 16:13:42",
        MODIFIED_BY: null,
        MODIFIED_DATE: "2024-05-22 18:27:10",
        JOB_DETAILS_ID: 7,
        PAGE_NO: null,
        id: 18,
      },
    ];
  },

  getProductsMini() {
    return Promise.resolve(this.getProductsData().slice(0, 50));
  },

  getProductsSmall() {
    return Promise.resolve(this.getProductsData().slice(0, 10));
  },

  getProducts() {
    return Promise.resolve(this.getProductsData());
  },

  getProductsWithOrdersSmall() {
    return Promise.resolve(this.getProductsWithOrdersData().slice(0, 10));
  },

  getProductsWithOrders() {
    return Promise.resolve(this.getProductsWithOrdersData());
  },
};
